#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def check_webinject_arguments(params):
    configfile, testfile, settings = params
    args = ""

    if "configfile":
        # USER4 is not available here.
        # So we use USER2 and go up to the home dir. Nasty.
        args += "-c $USER2$/../../../../etc/webinject/%s" % quote_shell_string(configfile)
    else:
        args += "-c not_configured_configfilename.xml"

    for setting in ['username', 'password']:
        if setting in settings:
            args += " -s \"%s=%s\"" % (setting.upper(), settings[setting])

    if "testfile":
        args += " $USER2$/../../../../etc/webinject/%s" % quote_shell_string(testfile)
    else:
        args += " not_configured_testfilename.xml"


    return args

active_check_info['webinject'] = {
    "command_line": 'PERL_LWP_SSL_VERIFY_HOSTNAME=0 $USER2$/check_webinject -o $USER4$/var/log/ $ARG1$',
    "argument_function": check_webinject_arguments,
    "service_description": lambda params: "WebInject" if params[0] == '$HOSTNAME$' else "WebInject %s" % params[0],
    "has_perfdata": True,
}
