#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def check_webinject_arguments(params):
    args = ""

    if "configfile" in params:
        args += "-c $USER4$/%s" % quote_shell_string(params["configfile"])
    else:
        args += "-c $USER4$/etc/webinject/config.xml"

    if "testfile" in params:
        args += " $USER4/etc/webinject/%s" % quote_shell_string(params["testfile"])
    else:
        args += " $USER4$/etc/webinject/testfile.xml"

    return args

def check_webinject_data_desc(params):
    if params[0].startswith("^"):
        return params[0][1:]
        return "WebInject %s" % params[0]

active_check_info['webinject'] = {
    "command_line": 'PERL_LWP_SSL_VERIFY_HOSTNAME=0 $USER2$/check_webinject -o $USER4$/etc/webinject/tmp/ $ARG1$',
    "argument_function": check_webinject_arguments,
    "service_description": check_webinject_data_desc,
    "has_perfdata": True,
}
